/* do not edit automatically generated by mc from CharClass.  */
/* CharClass.mod implement the ISO CharClass specification.

Copyright (C) 2002-2020 Free Software Foundation, Inc.
Contributed by Gaius Mulley <gaius.mulley@southwales.ac.uk>.

This file is part of GNU Modula-2.

GNU Modula-2 is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GNU Modula-2 is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */

#   if !defined (PROC_D)
#      define PROC_D
       typedef void (*PROC_t) (void);
       typedef struct { PROC_t proc; } PROC;
#   endif

#define _CharClass_H
#define _CharClass_C

#   include "GASCII.h"

unsigned int CharClass_IsNumeric (char ch);
unsigned int CharClass_IsLetter (char ch);
unsigned int CharClass_IsUpper (char ch);
unsigned int CharClass_IsLower (char ch);
unsigned int CharClass_IsControl (char ch);
unsigned int CharClass_IsWhiteSpace (char ch);

unsigned int CharClass_IsNumeric (char ch)
{
  /* Returns TRUE if and only if ch is classified as a numeric character  */
  return (ch >= '0') && (ch <= '9');
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

unsigned int CharClass_IsLetter (char ch)
{
  /* Returns TRUE if and only if ch is classified as a letter  */
  return ((ch >= 'a') && (ch <= 'z')) || ((ch >= 'A') && (ch <= 'Z'));
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

unsigned int CharClass_IsUpper (char ch)
{
  /* Returns TRUE if and only if ch is classified as an upper case letter  */
  return (ch >= 'A') && (ch <= 'Z');
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

unsigned int CharClass_IsLower (char ch)
{
  /* Returns TRUE if and only if ch is classified as a lower case letter  */
  return (ch >= 'a') && (ch <= 'z');
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

unsigned int CharClass_IsControl (char ch)
{
  /* Returns TRUE if and only if ch represents a control function  */
  return ch < ' ';
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

unsigned int CharClass_IsWhiteSpace (char ch)
{
  /* Returns TRUE if and only if ch represents a space character or a format effector  */
  return (((ch == ' ') || (ch == ASCII_cr)) || (ch == ASCII_lf)) || (ch == ASCII_tab);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

void _M2_CharClass_init (__attribute__((unused)) int argc, __attribute__((unused)) char *argv[])
{
}

void _M2_CharClass_finish (__attribute__((unused)) int argc, __attribute__((unused)) char *argv[])
{
}
