/* do not edit automatically generated by mc from EXCEPTIONS.  */
/* EXCEPTIONS.mod implement the ISO EXCEPTIONS specification.

Copyright (C) 2003-2020 Free Software Foundation, Inc.
Contributed by Gaius Mulley <gaius.mulley@southwales.ac.uk>.

This file is part of GNU Modula-2.

GNU Modula-2 is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GNU Modula-2 is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */

#   if !defined (PROC_D)
#      define PROC_D
       typedef void (*PROC_t) (void);
       typedef struct { PROC_t proc; } PROC;
#   endif

#include <stddef.h>
#include <string.h>
#include <limits.h>
#   include "GStorage.h"
#   include "Gmcrts.h"
#define _EXCEPTIONS_H
#define _EXCEPTIONS_C

#   include "GRTExceptions.h"
#   include "GM2EXCEPTION.h"
#   include "GM2RTS.h"
#   include "GASCII.h"
#   include "GSYSTEM.h"
#   include "GStorage.h"

typedef unsigned int EXCEPTIONS_ExceptionNumber;

typedef struct _T1_r _T1;

typedef _T1 *EXCEPTIONS_ExceptionSource;

struct _T1_r {
               RTExceptions_EHBlock eh;
             };

void EXCEPTIONS_AllocateSource (EXCEPTIONS_ExceptionSource *newSource);
void EXCEPTIONS_RAISE (EXCEPTIONS_ExceptionSource source, EXCEPTIONS_ExceptionNumber number, char *message_, unsigned int _message_high);
EXCEPTIONS_ExceptionNumber EXCEPTIONS_CurrentNumber (EXCEPTIONS_ExceptionSource source);
void EXCEPTIONS_GetMessage (char *text, unsigned int _text_high);
unsigned int EXCEPTIONS_IsCurrentSource (EXCEPTIONS_ExceptionSource source);
unsigned int EXCEPTIONS_IsExceptionalExecution (void);

void EXCEPTIONS_AllocateSource (EXCEPTIONS_ExceptionSource *newSource)
{
  /* Allocates a unique value of type ExceptionSource  */
  Storage_ALLOCATE ((void **) &(*newSource), sizeof (_T1));
  (*newSource)->eh = RTExceptions_InitExceptionBlock ();
}

void EXCEPTIONS_RAISE (EXCEPTIONS_ExceptionSource source, EXCEPTIONS_ExceptionNumber number, char *message_, unsigned int _message_high)
{
  char message[_message_high+1];

  /* make a local copy of each unbounded array.  */
  memcpy (message, message_, _message_high+1);

  /* Associates the given values of source, number and message with
     the current context and raises an exception.
  */
  RTExceptions_SetExceptionSource ((void *) source);
  RTExceptions_SetExceptionBlock (source->eh);
  RTExceptions_Raise ((unsigned int) number, "/home/gaius/GM2/graft-combine/gm2-floppsie/gcc/m2/gm2-libs-iso/EXCEPTIONS.mod", 65, 3, "RAISE", &message);
  /* we should never reach here as Raise should jump to the exception handler  */
  M2RTS_Halt ((char *) "/home/gaius/GM2/graft-combine/gm2-floppsie/gcc/m2/gm2-libs-iso/EXCEPTIONS.mod", 77, 67, (char *) "RAISE", 5, (char *) "should never return from RTException.Raise", 42);
}

EXCEPTIONS_ExceptionNumber EXCEPTIONS_CurrentNumber (EXCEPTIONS_ExceptionSource source)
{
  /* If the current coroutine is in the exceptional execution state
     because of the raising of an exception from source, returns the
     corresponding number, and otherwise raises an exception.
  */
  if (RTExceptions_IsInExceptionState ())
    {
      return RTExceptions_GetNumber (source->eh);
    }
  else
    {
      RTExceptions_Raise ( ((unsigned int) (M2EXCEPTION_coException)), "/home/gaius/GM2/graft-combine/gm2-floppsie/gcc/m2/gm2-libs-iso/EXCEPTIONS.mod", 82, 25, "CurrentNumber", "current coroutine is not in the exceptional execution state");
    }
  ReturnException ("/home/gaius/GM2/graft-combine/gm2-floppsie/gcc/m2/gm2-libs-iso/EXCEPTIONS.def", 10, 1);
  __builtin_unreachable ();
}

void EXCEPTIONS_GetMessage (char *text, unsigned int _text_high)
{
  unsigned int i;
  unsigned int h;
  char * p;

  /* If the current coroutine is in the exceptional execution state,
     returns the possibly truncated string associated with the
     current context.  Otherwise, in normal execution state,
     returns the empty string.
  */
  if (RTExceptions_IsInExceptionState ())
    {
      /* avoid dangling else.  */
      h = _text_high;
      i = 0;
      p = RTExceptions_GetTextBuffer (RTExceptions_GetExceptionBlock ());
      while ((p != NULL) && ((*p) != ASCII_nul))
        {
          text[i] = (*p);
          i += 1;
          p += 1;
        }
      if (i <= h)
        {
          text[i] = ASCII_nul;
        }
    }
  else
    {
      text[0] = ASCII_nul;
    }
}

unsigned int EXCEPTIONS_IsCurrentSource (EXCEPTIONS_ExceptionSource source)
{
  /* If the current coroutine is in the exceptional execution state
     because of the raising of an exception from source, returns TRUE,
     and otherwise returns FALSE.
  */
  return (RTExceptions_IsInExceptionState ()) && (source == (RTExceptions_GetExceptionSource ()));
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

unsigned int EXCEPTIONS_IsExceptionalExecution (void)
{
  /* If the current coroutine is in the exceptional execution state
     because of the raising of an exception, returns TRUE,
     and otherwise returns FALSE.
  */
  return RTExceptions_IsInExceptionState ();
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

void _M2_EXCEPTIONS_init (__attribute__((unused)) int argc, __attribute__((unused)) char *argv[])
{
}

void _M2_EXCEPTIONS_finish (__attribute__((unused)) int argc, __attribute__((unused)) char *argv[])
{
}
