/* do not edit automatically generated by mc from MemStream.  */
/* MemStream.def provide a memory stream channel.

Copyright (C) 2015-2020 Free Software Foundation, Inc.
Contributed by Gaius Mulley <gaius.mulley@southwales.ac.uk>.

This file is part of GNU Modula-2.

GNU Modula-2 is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GNU Modula-2 is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */


#if !defined (_MemStream_H)
#   define _MemStream_H

#   ifdef __cplusplus
extern "C" {
#   endif
#   if !defined (PROC_D)
#      define PROC_D
       typedef void (*PROC_t) (void);
       typedef struct { PROC_t proc; } PROC;
#   endif

#   include "GIOChan.h"
#   include "GChanConsts.h"
#   include "GSYSTEM.h"

#   if defined (_MemStream_C)
#      define EXTERN
#   else
#      define EXTERN extern
#   endif

EXTERN void MemStream_OpenWrite (IOChan_ChanId *cid, ChanConsts_FlagSet flags, ChanConsts_OpenResults *res, void * *buffer, unsigned int *length, unsigned int *used, unsigned int deallocOnClose);
EXTERN void MemStream_OpenRead (IOChan_ChanId *cid, ChanConsts_FlagSet flags, ChanConsts_OpenResults *res, void * buffer, unsigned int length, unsigned int deallocOnClose);

/*
   Close - if the channel identified by cid is not open to
           a memory stream, the exception wrongDevice is
           raised; otherwise closes the channel, and assigns
           the value identifying the invalid channel to cid.
*/

EXTERN void MemStream_Close (IOChan_ChanId *cid);

/*
   Rewrite - assigns the buffer index to zero.  Subsequent
             writes will overwrite the previous buffer contents.
*/

EXTERN void MemStream_Rewrite (IOChan_ChanId cid);

/*
   Reread - assigns the buffer index to zero.  Subsequent
            reads will read the previous buffer contents.
*/

EXTERN void MemStream_Reread (IOChan_ChanId cid);

/*
   IsMem - tests if the channel identified by cid is open as
           a memory stream.
*/

EXTERN unsigned int MemStream_IsMem (IOChan_ChanId cid);
#   ifdef __cplusplus
}
#   endif

#   undef EXTERN
#endif
