/* do not edit automatically generated by mc from NetworkOrder.  */
/* This file is part of GNU Modula-2.

GNU Modula-2 is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GNU Modula-2 is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License along
with gm2; see the file COPYING.  If not, write to the Free Software
Foundation, 51 Franklin Street, Fifth Floor,
Boston, MA 02110-1301, USA.  */


#if !defined (_NetworkOrder_H)
#   define _NetworkOrder_H

#   ifdef __cplusplus
extern "C" {
#   endif
#   if !defined (PROC_D)
#      define PROC_D
       typedef void (*PROC_t) (void);
       typedef struct { PROC_t proc; } PROC;
#   endif

#   include "GPoints.h"
#   include "GFractions.h"
#   include "Gcoord.h"
#   include "GIOChan.h"

#   if defined (_NetworkOrder_C)
#      define EXTERN
#   else
#      define EXTERN extern
#   endif


/*
   writeReal - 
*/

EXTERN void NetworkOrder_writeReal (IOChan_ChanId file, double r);

/*
   writeCard - 
*/

EXTERN void NetworkOrder_writeCard (IOChan_ChanId file, unsigned int c);

/*
   writeFract - 
*/

EXTERN void NetworkOrder_writeFract (IOChan_ChanId file, Fractions_Fract f);

/*
   writePoint - 
*/

EXTERN void NetworkOrder_writePoint (IOChan_ChanId file, Points_Point p);

/*
   writeCoord - 
*/

EXTERN void NetworkOrder_writeCoord (IOChan_ChanId file, coord_Coord c);

/*
   writeLongCard - 
*/

EXTERN void NetworkOrder_writeLongCard (IOChan_ChanId file, long unsigned int l);

/*
   writeShort - 
*/

EXTERN void NetworkOrder_writeShort (IOChan_ChanId file, short unsigned int s);
#   ifdef __cplusplus
}
#   endif

#   undef EXTERN
#endif
