/* do not edit automatically generated by mc from RTgenif.  */
/* RTgenif.def provide a generic device interface mechanism used by RTgen.

Copyright (C) 2008-2020 Free Software Foundation, Inc.
Contributed by Gaius Mulley <gaius.mulley@southwales.ac.uk>.

This file is part of GNU Modula-2.

GNU Modula-2 is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GNU Modula-2 is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */


#if !defined (_RTgenif_H)
#   define _RTgenif_H

#   ifdef __cplusplus
extern "C" {
#   endif
#   if !defined (PROC_D)
#      define PROC_D
       typedef void (*PROC_t) (void);
       typedef struct { PROC_t proc; } PROC;
#   endif

#   include "GSYSTEM.h"
#   include "GIOLink.h"

#   if defined (_RTgenif_C)
#      define EXTERN
#   else
#      define EXTERN extern
#   endif

#if !defined (RTgenif_GenDevIF_D)
#  define RTgenif_GenDevIF_D
   typedef void *RTgenif_GenDevIF;
#endif

typedef struct RTgenif_readchar_p RTgenif_readchar;

typedef struct RTgenif_unreadchar_p RTgenif_unreadchar;

typedef struct RTgenif_geterrno_p RTgenif_geterrno;

typedef struct RTgenif_readbytes_p RTgenif_readbytes;

typedef struct RTgenif_writebytes_p RTgenif_writebytes;

typedef struct RTgenif_writeln_p RTgenif_writeln;

typedef struct RTgenif_iseof_p RTgenif_iseof;

typedef struct RTgenif_iseoln_p RTgenif_iseoln;

typedef struct RTgenif_iserror_p RTgenif_iserror;

typedef char (*RTgenif_readchar_t) (RTgenif_GenDevIF, IOLink_DeviceTablePtr);
struct RTgenif_readchar_p { RTgenif_readchar_t proc; };

typedef char (*RTgenif_unreadchar_t) (RTgenif_GenDevIF, IOLink_DeviceTablePtr, char);
struct RTgenif_unreadchar_p { RTgenif_unreadchar_t proc; };

typedef int (*RTgenif_geterrno_t) (RTgenif_GenDevIF, IOLink_DeviceTablePtr);
struct RTgenif_geterrno_p { RTgenif_geterrno_t proc; };

typedef unsigned int (*RTgenif_readbytes_t) (RTgenif_GenDevIF, IOLink_DeviceTablePtr, void *, unsigned int, unsigned int *);
struct RTgenif_readbytes_p { RTgenif_readbytes_t proc; };

typedef unsigned int (*RTgenif_writebytes_t) (RTgenif_GenDevIF, IOLink_DeviceTablePtr, void *, unsigned int, unsigned int *);
struct RTgenif_writebytes_p { RTgenif_writebytes_t proc; };

typedef unsigned int (*RTgenif_writeln_t) (RTgenif_GenDevIF, IOLink_DeviceTablePtr);
struct RTgenif_writeln_p { RTgenif_writeln_t proc; };

typedef unsigned int (*RTgenif_iseof_t) (RTgenif_GenDevIF, IOLink_DeviceTablePtr);
struct RTgenif_iseof_p { RTgenif_iseof_t proc; };

typedef unsigned int (*RTgenif_iseoln_t) (RTgenif_GenDevIF, IOLink_DeviceTablePtr);
struct RTgenif_iseoln_p { RTgenif_iseoln_t proc; };

typedef unsigned int (*RTgenif_iserror_t) (RTgenif_GenDevIF, IOLink_DeviceTablePtr);
struct RTgenif_iserror_p { RTgenif_iserror_t proc; };


/*
   InitGenDevIF - initializes a generic device.
*/

EXTERN RTgenif_GenDevIF RTgenif_InitGenDevIF (IOLink_DeviceId d, RTgenif_readchar rc, RTgenif_unreadchar urc, RTgenif_geterrno geterr, RTgenif_readbytes rbytes, RTgenif_writebytes wbytes, RTgenif_writeln wl, RTgenif_iseof eof, RTgenif_iseoln eoln, RTgenif_iserror iserr);

/*
   getDID - returns the device id this generic interface.
*/

EXTERN IOLink_DeviceId RTgenif_getDID (RTgenif_GenDevIF g);

/*
   doReadChar - returns the next character from the generic
                device.
*/

EXTERN char RTgenif_doReadChar (RTgenif_GenDevIF g, IOLink_DeviceTablePtr d);

/*
   doUnReadChar - pushes back a character to the generic device.
*/

EXTERN char RTgenif_doUnReadChar (RTgenif_GenDevIF g, IOLink_DeviceTablePtr d, char ch);

/*
   doGetErrno - returns the errno relating to the generic device.
*/

EXTERN int RTgenif_doGetErrno (RTgenif_GenDevIF g, IOLink_DeviceTablePtr d);

/*
   doRBytes - attempts to read, n, bytes from the generic device.
              It set the actual amount read and returns a boolean
              to determine whether an error occurred.
*/

EXTERN unsigned int RTgenif_doRBytes (RTgenif_GenDevIF g, IOLink_DeviceTablePtr d, void * to, unsigned int max, unsigned int *actual);

/*
   doWBytes - attempts to write, n, bytes to the generic device.
              It sets the actual amount written and returns a
              boolean to determine whether an error occurred.
*/

EXTERN unsigned int RTgenif_doWBytes (RTgenif_GenDevIF g, IOLink_DeviceTablePtr d, void * from, unsigned int max, unsigned int *actual);

/*
   doWrLn - writes an end of line marker and returns
            TRUE if successful.
*/

EXTERN unsigned int RTgenif_doWrLn (RTgenif_GenDevIF g, IOLink_DeviceTablePtr d);

/*
   isEOF - returns true if the end of file was reached.
*/

EXTERN unsigned int RTgenif_isEOF (RTgenif_GenDevIF g, IOLink_DeviceTablePtr d);

/*
   isEOLN - returns true if the end of line was reached.
*/

EXTERN unsigned int RTgenif_isEOLN (RTgenif_GenDevIF g, IOLink_DeviceTablePtr d);

/*
   isError - returns true if an error was seen in the device.
*/

EXTERN unsigned int RTgenif_isError (RTgenif_GenDevIF g, IOLink_DeviceTablePtr d);

/*
   KillGenDevIF - deallocates a generic device.
*/

EXTERN RTgenif_GenDevIF RTgenif_KillGenDevIF (RTgenif_GenDevIF g);
#   ifdef __cplusplus
}
#   endif

#   undef EXTERN
#endif
