/* do not edit automatically generated by mc from Transform3D.  */
/* This file is part of GNU Modula-2.

GNU Modula-2 is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GNU Modula-2 is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License along
with gm2; see the file COPYING.  If not, write to the Free Software
Foundation, 51 Franklin Street, Fifth Floor,
Boston, MA 02110-1301, USA.  */


#if !defined (_Transform3D_H)
#   define _Transform3D_H

#   ifdef __cplusplus
extern "C" {
#   endif
#   if !defined (PROC_D)
#      define PROC_D
       typedef void (*PROC_t) (void);
       typedef struct { PROC_t proc; } PROC;
#   endif

#   include "GPolyMatrix3D.h"
#   include "GFractions.h"
#   include "GPoints.h"

#   if defined (_Transform3D_C)
#      define EXTERN
#   else
#      define EXTERN extern
#   endif


/*
   reflect - returns a Matrix representing the reflect
             transformation in line: y = mx + c.
*/

EXTERN PolyMatrix3D_Matrix Transform3D_reflect (Fractions_Fract m, Fractions_Fract x, Fractions_Fract c);

/*
   rotate - returns a Matrix representing the rotate
            transformation about 0, 0 with r radians.
*/

EXTERN PolyMatrix3D_Matrix Transform3D_rotate (Fractions_Fract r);

/*
   scale - returns a Matrix representing the scale
           transformation by vector, p.
*/

EXTERN PolyMatrix3D_Matrix Transform3D_scale (Points_Point p);

/*
   translate - returns a Matrix representing the translate
               transformation by vector, p.
*/

EXTERN PolyMatrix3D_Matrix Transform3D_translate (Points_Point p);
#   ifdef __cplusplus
}
#   endif

#   undef EXTERN
#endif
