/* do not edit automatically generated by mc from MathLib0.  */
/* MathLib0.mod provides access to math functions.

Copyright (C) 2003-2020 Free Software Foundation, Inc.
Contributed by Gaius Mulley <gaius.mulley@southwales.ac.uk>.

This file is part of GNU Modula-2.

GNU Modula-2 is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GNU Modula-2 is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */

#   if !defined (PROC_D)
#      define PROC_D
       typedef void (*PROC_t) (void);
       typedef struct { PROC_t proc; } PROC;
#   endif

#   include <complex.h>
#define _MathLib0_H
#define _MathLib0_C

#   include "Gcbuiltin.h"
#   include "Glibm.h"

#   define MathLib0_pi 3.1415926535897932384626433832795028841972
#   define MathLib0_exp1 2.7182818284590452353602874713526624977572
double MathLib0_sqrt (double x);
double MathLib0_exp (double x);
double MathLib0_ln (double x);
double MathLib0_sin (double x);
double MathLib0_cos (double x);
double MathLib0_tan (double x);
double MathLib0_arctan (double x);
int MathLib0_entier (double x);
static long double sqrtl (long double x);
static float sqrts (float x);
static float exps (float x);
static long double expl (long double x);
static float lns (float x);
static long double lnl (long double x);
static long double sinl (long double x);
static float sins (float x);
static float coss (float x);
static long double cosl (long double x);
static long double tanl (long double x);
static float tans (float x);
static float arctans (float x);
static long double arctanl (long double x);
static int entiers (float x);
static int entierl (long double x);

static long double sqrtl (long double x)
{
  return cbuiltin_sqrtl (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static float sqrts (float x)
{
  return cbuiltin_sqrtf (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static float exps (float x)
{
  return libm_expf (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static long double expl (long double x)
{
  return libm_expl (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static float lns (float x)
{
  return (libm_logf (x))/(libm_logf (MathLib0_exp1));
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static long double lnl (long double x)
{
  return (libm_logl (x))/(libm_logl (MathLib0_exp1));
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static long double sinl (long double x)
{
  return cbuiltin_sinl (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static float sins (float x)
{
  return cbuiltin_sinf (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static float coss (float x)
{
  return cbuiltin_cosf (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static long double cosl (long double x)
{
  return cbuiltin_cosl (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static long double tanl (long double x)
{
  return libm_tanl (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static float tans (float x)
{
  return libm_tanf (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static float arctans (float x)
{
  return libm_atanf (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static long double arctanl (long double x)
{
  return libm_atanl (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static int entiers (float x)
{
  return ((int) (libm_floorf (x)));
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

static int entierl (long double x)
{
  return ((int) (libm_floorl (x)));
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

double MathLib0_sqrt (double x)
{
  return cbuiltin_sqrt (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

double MathLib0_exp (double x)
{
  return libm_exp (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

double MathLib0_ln (double x)
{
  /* 
                log (b)
   log (b)  =      c
      a         ------
                log (a)
                   c
  */
  return (libm_log (x))/(libm_log (MathLib0_exp1));
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

double MathLib0_sin (double x)
{
  return cbuiltin_sin (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

double MathLib0_cos (double x)
{
  return cbuiltin_cos (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

double MathLib0_tan (double x)
{
  return libm_tan (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

double MathLib0_arctan (double x)
{
  return libm_atan (x);
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

int MathLib0_entier (double x)
{
  return ((int) (libm_floor (x)));
  /* static analysis guarentees a RETURN statement will be used before here.  */
  __builtin_unreachable ();
}

void _M2_MathLib0_init (__attribute__((unused)) int argc, __attribute__((unused)) char *argv[])
{
}

void _M2_MathLib0_finish (__attribute__((unused)) int argc, __attribute__((unused)) char *argv[])
{
}
